/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface AttestationRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "attestations" | "postAttestation"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AttestationPosted"): EventFragment;

  encodeFunctionData(
    functionFragment: "attestations",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "postAttestation",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "attestations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "postAttestation",
    data: BytesLike
  ): Result;
}

export namespace AttestationPostedEvent {
  export type InputTuple = [jobId: BytesLike, attestationHash: BytesLike];
  export type OutputTuple = [jobId: string, attestationHash: string];
  export interface OutputObject {
    jobId: string;
    attestationHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AttestationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AttestationRegistry;
  waitForDeployment(): Promise<this>;

  interface: AttestationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attestations: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  postAttestation: TypedContractMethod<
    [jobId: BytesLike, attestationHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attestations"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "postAttestation"
  ): TypedContractMethod<
    [jobId: BytesLike, attestationHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AttestationPosted"
  ): TypedContractEvent<
    AttestationPostedEvent.InputTuple,
    AttestationPostedEvent.OutputTuple,
    AttestationPostedEvent.OutputObject
  >;

  filters: {
    "AttestationPosted(bytes32,bytes32)": TypedContractEvent<
      AttestationPostedEvent.InputTuple,
      AttestationPostedEvent.OutputTuple,
      AttestationPostedEvent.OutputObject
    >;
    AttestationPosted: TypedContractEvent<
      AttestationPostedEvent.InputTuple,
      AttestationPostedEvent.OutputTuple,
      AttestationPostedEvent.OutputObject
    >;
  };
}
