/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ProviderRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deregister"
      | "getActiveProviders"
      | "providerList"
      | "providers"
      | "register"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ProviderDeregistered" | "ProviderRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deregister",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveProviders",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "providerList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "providers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [string, string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "deregister", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getActiveProviders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "providerList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "providers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
}

export namespace ProviderDeregisteredEvent {
  export type InputTuple = [provider: AddressLike];
  export type OutputTuple = [provider: string];
  export interface OutputObject {
    provider: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProviderRegisteredEvent {
  export type InputTuple = [
    provider: AddressLike,
    endpoint: string,
    model: string,
    pricePerToken: BigNumberish
  ];
  export type OutputTuple = [
    provider: string,
    endpoint: string,
    model: string,
    pricePerToken: bigint
  ];
  export interface OutputObject {
    provider: string;
    endpoint: string;
    model: string;
    pricePerToken: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProviderRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ProviderRegistry;
  waitForDeployment(): Promise<this>;

  interface: ProviderRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deregister: TypedContractMethod<[], [void], "nonpayable">;

  getActiveProviders: TypedContractMethod<[], [string[]], "view">;

  providerList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  providers: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, boolean] & {
        endpoint: string;
        model: string;
        pricePerToken: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  register: TypedContractMethod<
    [endpoint: string, model: string, pricePerToken: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deregister"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActiveProviders"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "providerList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "providers"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, boolean] & {
        endpoint: string;
        model: string;
        pricePerToken: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<
    [endpoint: string, model: string, pricePerToken: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ProviderDeregistered"
  ): TypedContractEvent<
    ProviderDeregisteredEvent.InputTuple,
    ProviderDeregisteredEvent.OutputTuple,
    ProviderDeregisteredEvent.OutputObject
  >;
  getEvent(
    key: "ProviderRegistered"
  ): TypedContractEvent<
    ProviderRegisteredEvent.InputTuple,
    ProviderRegisteredEvent.OutputTuple,
    ProviderRegisteredEvent.OutputObject
  >;

  filters: {
    "ProviderDeregistered(address)": TypedContractEvent<
      ProviderDeregisteredEvent.InputTuple,
      ProviderDeregisteredEvent.OutputTuple,
      ProviderDeregisteredEvent.OutputObject
    >;
    ProviderDeregistered: TypedContractEvent<
      ProviderDeregisteredEvent.InputTuple,
      ProviderDeregisteredEvent.OutputTuple,
      ProviderDeregisteredEvent.OutputObject
    >;

    "ProviderRegistered(address,string,string,uint256)": TypedContractEvent<
      ProviderRegisteredEvent.InputTuple,
      ProviderRegisteredEvent.OutputTuple,
      ProviderRegisteredEvent.OutputObject
    >;
    ProviderRegistered: TypedContractEvent<
      ProviderRegisteredEvent.InputTuple,
      ProviderRegisteredEvent.OutputTuple,
      ProviderRegisteredEvent.OutputObject
    >;
  };
}
