/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type {
  AttestationRegistry,
  AttestationRegistryInterface,
} from "../AttestationRegistry";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "jobId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "attestationHash",
        type: "bytes32",
      },
    ],
    name: "AttestationPosted",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "attestations",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "jobId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "attestationHash",
        type: "bytes32",
      },
    ],
    name: "postAttestation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506101fa806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063940992a31461003b578063ca7c74951461006b575b600080fd5b6100556004803603810190610050919061012d565b610087565b6040516100629190610169565b60405180910390f35b61008560048036038101906100809190610184565b61009f565b005b60006020528060005260406000206000915090505481565b8060008084815260200190815260200160002081905550817f248ec70898681d82dc37898e4348b6127e06838197d231f37d3ef49b7e47b784826040516100e69190610169565b60405180910390a25050565b600080fd5b6000819050919050565b61010a816100f7565b811461011557600080fd5b50565b60008135905061012781610101565b92915050565b600060208284031215610143576101426100f2565b5b600061015184828501610118565b91505092915050565b610163816100f7565b82525050565b600060208201905061017e600083018461015a565b92915050565b6000806040838503121561019b5761019a6100f2565b5b60006101a985828601610118565b92505060206101ba85828601610118565b915050925092905056fea264697066735822122048be2ed7721b874dbc8f5dff9e7a0424d56faff2c4fb94abca36f6d8844e512964736f6c63430008140033";

type AttestationRegistryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AttestationRegistryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AttestationRegistry__factory extends ContractFactory {
  constructor(...args: AttestationRegistryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      AttestationRegistry & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): AttestationRegistry__factory {
    return super.connect(runner) as AttestationRegistry__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AttestationRegistryInterface {
    return new Interface(_abi) as AttestationRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AttestationRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as AttestationRegistry;
  }
}
